### ISSUE TITLE
question about decision table, column Med(SB2018/ 0.30SB0)

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/csas-latex#82]
@cgrandin Can you please post the equation for the 3rd column of the decision table? I tried rough calculating by hand and get different values. Thx.

**Comment by cgrandin** [comment]
`median(d[,"B2018"] / d$X03B0`
where d is the data frame from the file iscammcmc_proj_Gear1.csv

I just looked at the iscam code though and the projection code is outputting bo instead of sbo so this might be an error in the document. How are you calculating it?

**Comment by jaclyncleary** [comment]
I just tried calculating by hand using median values (just for approximation).
Eg, HG AM2
SB_2018= 3.270
0.30*SB_0= 6.929
SB_2018/ 0.30*SB_0= 0.47 whereas the decision table has 0.77

Is it possible that bo is being used by the 3rd column but sbo by the 2nd column?
The reason I ask is because the values in the 2nd column "match" Figure 29.

I will look carefully at iscam code.

**Comment by cgrandin** [comment]
I see the problem. The decision table is wrong because it is using the 03BO column, which is wrong. I think this means we have to run all the mcevals again once I fix it. Sigh. In iscam-pbs, look at line 5934. This one:
`   write_proj_output(ofsmcmc, syr, nyr, nage, tac, pyr,`
`                     p_sbt, p_ft, p_N, M, ma, dWt_bar, ft(1),`
`                     bo, fmsy, bmsy, !d_iscamCntrl(13),`
`                     d_iscamCntrl(13) && d_iscamCntrl(20));`

it is sending bo, not sbo. So everything in the decision table that relies on sbo is using bo instead. Sorry I missed this.

**Comment by cgrandin** [comment]
I fixed the iscam code, and re-ran the mceval for HG AM2 only, then rebuilt the doc. Note only the HG AM2 table has changed, but not by that much. Instead of 0.77, it is 0.63 for the TAC=0 case.

You'll also see that column 2 changed. Columns 2 and 3 are both using the 03B0 column in the mcmc projection file.
I sent it to your email

I pushed my changes to iscam-pbs so you can run mceval on the models with decision tables

**Comment by jaclyncleary** [comment]
thanks, looking now.

**Comment by Shawkshaw** [comment]
I reran the mceval for the base case for all stock and they have been updated in the Herring repo.  I am still having trouble building the resdoc pdf so I can not check the changes to the decision tables

**Comment by jaclyncleary** [comment]
merging now

**Comment by jaclyncleary** [comment]
I've recreated tables. Please confirm that I only needed to copy the iscammcmc_proj_Gear1.csv files from Herring/2017mcmc/models/HG...PRD...CC...SOG...WCVI to csas-latex/models/

**Comment by Shawkshaw** [comment]
Yes, that was the only file that was changed
